services:
  db:
    image: mongo
    container_name: kryvea-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kryveauser
      - MONGO_INITDB_ROOT_PASSWORD=kryveapass
    volumes:
      - kryvea-db-storage:/data/db
    networks:
      - kryvea-net
    restart: unless-stopped

  app:
    build: app
    container_name: kryvea-app
    environment:
      - KRYVEA_ADDR=0.0.0.0:80
      - KRYVEA_ROOT_PATH=/
      - KRYVEA_MONGO_URI=mongodb://kryveauser:kryveapass@kryvea-db:27017
    volumes:
      - kryvea-static:/opt/kryvea/static
      - /var/local/kryvea/log:/var/log/kryvea/
    depends_on:
      - db
    networks:
      - kryvea-net
    restart: unless-stopped

  web:
    build: nginx
    container_name: kryvea-nginx
    volumes:
      - kryvea-static:/var/www/kryvea/html/static
      - /var/local/kryvea/ssl:/etc/nginx/ssl
    depends_on:
      - db
      - app
    ports:
      - 443:443
    networks:
      - kryvea-net
    restart: unless-stopped

networks:
  kryvea-net:
    driver: bridge

volumes:
  kryvea-db-storage:
  kryvea-static:
