export const categories = [
  {
    id: "67ae841b596db351cbcd096b",
    created_at: "2025-02-13T23:45:31.384Z",
    updated_at: "2025-02-13T23:45:31.384Z",
    index: "KvQIFmay",
    name: "Luna Atlas Ryder",
    source: "",
    generic_description: {
      de: "Sable Nyx Aria Rogue Juno Lyric Kai Echo Orion Luna Storm Zephyr Sable Dash Titan Hawk Dante Hawk Ember Rogue Ember Ace Vega Skye Vega Phoenix Nyx Orion Lyric Atlas Kairos Titan Sable Nyx Hunter Xander Storm Shadow Indigo Orion Hawk Xander Lyric Atlas Titan Kairos Sable Zane Kai Ember",
      en: "Ace Ryder Xander Aria Maverick Blaze Knox Nyx Onyx Lyric Zephyr Juno Titan Blaze Aspen Vega Aspen Skye Zephyr Luna Juno Knox Ember Dash Skye Nyx Xander Sable Zane Zara Ember Hunter Hawk Ace Indigo Hunter Jett Aria Skye Echo Jett Storm Zane Zara Blaze Orion Ryder Shadow Nyx Aspen",
      es: "Hunter Echo Zara Echo Juno Kairos Titan Phoenix Ember Juno Blaze Aria Kairos Dante Maverick Knox Echo Blaze Sable Storm Zara Indigo Hunter Shadow Hunter Zara Zara Blaze Zane Juno Sage Indigo Ember Knox Dante Kairos Nyx Skye Kai Luna Onyx Kai Hawk Lyric Nyx Kai Maverick Echo Zara Onyx",
      it: "Nyx Shadow Hunter Vega Skye Dash Blaze Hawk Vega Kairos Vega Ember Rogue Phoenix Nova Shadow Zephyr Maverick Skye Kairos Echo Ace Xander Blaze Ryder Xander Echo Blaze Dash Zephyr Luna Nova Vega Sable Zane Maverick Nova Ace Vega Ace Hawk Nova Hunter Knox Shadow Sable Xander Sage Nyx Storm",
    },
    generic_remediation: {
      de: "Kai Aria Skye Nyx Hawk Titan Maverick Lyric Titan Raven Kai Phoenix Knox Kairos Raven Luna Zane Zane Orion Zephyr Ace Nyx Sage Orion Maverick Lyric Shadow Ryder Onyx Nova Zephyr Xander Aria Titan Echo Aria Sable Lyric Nyx Orion Indigo Phoenix Aria Zane Zane Orion Kai Vega Jett Echo",
      en: "Ember Aria Atlas Ace Raven Skye Lyric Indigo Vega Axel Ember Nova Dash Lyric Onyx Titan Nyx Dash Sable Sage Onyx Titan Echo Ace Ace Nova Dante Zane Lyric Onyx Echo Storm Ember Xander Titan Maverick Lyric Onyx Nova Shadow Zara Sable Nova Sage Atlas Shadow Kai Indigo Dante Maverick",
      es: "Aspen Phoenix Echo Xander Dante Skye Knox Shadow Echo Sable Nyx Zane Raven Raven Orion Ryder Hawk Nyx Ace Xander Juno Aria Ember Hawk Onyx Nyx Juno Onyx Aria Kairos Storm Zephyr Aspen Storm Knox Orion Dante Sable Luna Hawk Phoenix Hawk Blaze Rogue Dante Sable Indigo Titan Sage Skye",
      it: "Sable Zara Dante Ace Knox Kai Hawk Sage Luna Hunter Ember Jett Nova Indigo Ace Zephyr Rogue Storm Jett Dante Phoenix Zane Aria Xander Ace Sage Zane Orion Echo Indigo Rogue Zephyr Shadow Storm Zane Kairos Raven Knox Juno Phoenix Raven Aria Maverick Dante Ace Dash Storm Blaze Sable Jett",
    },
  },
  {
    id: "67ae841b596db351cbcd096c",
    created_at: "2025-02-13T23:45:31.493Z",
    updated_at: "2025-02-13T23:45:31.493Z",
    index: "vZCndrew",
    name: "Luna Echo Hunter",
    source: "",
    generic_description: {
      de: "Knox Ember Blaze Echo Kai Maverick Sable Kai Juno Xander Ace Zephyr Onyx Ryder Ember Shadow Hunter Lyric Ember Zane Ryder Sable Hawk Orion Skye Onyx Shadow Ace Indigo Sable Hawk Dash Xander Indigo Rogue Xander Atlas Skye Rogue Onyx Zara Ember Ryder Sable Juno Blaze Ember Axel Dash Sage",
      fr: "Nyx Atlas Nyx Hunter Aspen Nova Zara Aspen Juno Blaze Lyric Onyx Nova Axel Axel Rogue Luna Storm Sable Zara Rogue Dante Ryder Skye Axel Dante Orion Onyx Kai Echo Ace Axel Rogue Echo Knox Kairos Phoenix Sage Raven Onyx Jett Zephyr Sable Shadow Xander Shadow Maverick Vega Dante Vega",
      it: "Hunter Ember Blaze Hawk Zane Ember Nyx Sage Ember Dash Zara Ember Blaze Knox Phoenix Blaze Sable Xander Ember Echo Rogue Atlas Zara Storm Orion Zane Phoenix Orion Kai Nova Jett Nova Aria Shadow Kai Skye Zephyr Kairos Knox Zephyr Nova Juno Xander Indigo Kairos Jett Aria Phoenix Storm Knox",
    },
    generic_remediation: {
      de: "Orion Kai Echo Skye Dash Zephyr Ace Lyric Zane Aspen Axel Knox Vega Sable Kairos Nova Titan Jett Atlas Rogue Shadow Phoenix Ryder Axel Onyx Knox Rogue Kai Zara Zara Ember Atlas Jett Axel Echo Zara Shadow Rogue Blaze Sage Kai Titan Ryder Titan Phoenix Orion Sable Zane Kairos Blaze",
      fr: "Zane Dante Shadow Juno Zane Hunter Shadow Dash Shadow Shadow Phoenix Titan Knox Ryder Storm Shadow Hunter Onyx Onyx Luna Knox Skye Kai Xander Vega Zara Axel Nova Skye Sage Xander Titan Dash Skye Nyx Echo Maverick Nyx Atlas Ryder Sage Zane Titan Knox Phoenix Aria Xander Ember Luna Zephyr",
      it: "Blaze Sage Jett Atlas Raven Phoenix Nova Sage Maverick Sage Blaze Aspen Zephyr Maverick Xander Dash Aria Titan Blaze Luna Axel Nova Nyx Aspen Lyric Ryder Indigo Atlas Hunter Nyx Rogue Nova Onyx Phoenix Onyx Nyx Phoenix Zane Nova Knox Raven Xander Sage Sable Ryder Orion Maverick Maverick Axel Ember",
    },
  },
  {
    id: "67ae841b596db351cbcd096d",
    created_at: "2025-02-13T23:45:31.601Z",
    updated_at: "2025-02-13T23:45:31.601Z",
    index: "DDXcRBAC",
    name: "Onyx Zane Zephyr",
    source: "",
    generic_description: {
      en: "Hunter Sage Zane Lyric Xander Ryder Hawk Axel Phoenix Xander Zara Shadow Indigo Knox Ryder Xander Dante Skye Lyric Vega Knox Sage Phoenix Lyric Knox Ryder Indigo Nova Jett Luna Onyx Ryder Dash Zane Raven Nyx Lyric Hunter Onyx Raven Nova Zara Ace Aria Lyric Hawk Vega Skye Maverick Ace",
      es: "Zephyr Skye Titan Atlas Jett Luna Storm Shadow Sable Echo Knox Luna Onyx Echo Zane Kai Ryder Juno Atlas Storm Indigo Lyric Rogue Dante Kai Xander Atlas Luna Phoenix Storm Hunter Axel Aspen Ace Ember Atlas Hunter Kairos Atlas Nova Dash Rogue Indigo Zephyr Hunter Ember Storm Nova Zane Luna",
      fr: "Jett Luna Hunter Atlas Orion Rogue Aspen Shadow Xander Maverick Jett Knox Titan Hunter Zara Phoenix Zephyr Nova Jett Zara Vega Dante Skye Orion Hunter Phoenix Rogue Vega Kai Juno Raven Atlas Vega Zephyr Jett Xander Kai Aspen Storm Echo Dante Ryder Knox Maverick Vega Luna Shadow Dash Orion Onyx",
      it: "Kairos Maverick Skye Dash Kairos Hunter Hunter Lyric Dash Storm Knox Storm Axel Maverick Ryder Maverick Lyric Ace Skye Nyx Kairos Titan Raven Titan Raven Shadow Axel Juno Aspen Axel Shadow Juno Phoenix Nyx Onyx Dash Blaze Xander Knox Sable Echo Phoenix Dante Titan Raven Aspen Sable Lyric Storm Xander",
    },
    generic_remediation: {
      en: "Aspen Phoenix Atlas Jett Hawk Jett Luna Sage Skye Atlas Zephyr Zara Xander Luna Sable Kai Aspen Kai Ryder Luna Maverick Ember Echo Lyric Echo Aria Juno Sable Hawk Dante Echo Sable Jett Sable Blaze Jett Dante Aria Axel Lyric Shadow Maverick Blaze Indigo Luna Kai Nova Ember Aria Nyx",
      es: "Nova Juno Sage Raven Kairos Orion Dante Blaze Indigo Ember Echo Vega Kairos Hawk Maverick Lyric Ember Orion Lyric Zephyr Indigo Jett Hawk Ember Zephyr Axel Onyx Raven Kai Knox Kairos Hawk Kai Atlas Nova Rogue Sable Juno Kairos Dash Zane Atlas Sage Zane Orion Dante Phoenix Vega Luna Sage",
      fr: "Atlas Vega Atlas Nyx Lyric Hunter Aspen Kai Jett Dash Kairos Ember Jett Dante Nyx Maverick Jett Orion Blaze Ryder Ace Onyx Kai Vega Knox Shadow Ryder Maverick Nyx Echo Echo Luna Phoenix Titan Skye Jett Ember Atlas Blaze Phoenix Nova Vega Kairos Dash Sage Vega Ryder Dash Phoenix Skye",
      it: "Xander Titan Juno Onyx Vega Dash Luna Titan Dash Ryder Sage Sable Maverick Lyric Ryder Jett Jett Luna Shadow Aria Juno Phoenix Skye Jett Luna Hunter Shadow Phoenix Shadow Jett Aria Echo Zephyr Dash Dante Kai Ryder Kairos Maverick Knox Sage Ryder Phoenix Dash Juno Rogue Skye Nyx Xander Ace",
    },
  },
  {
    id: "67ae841b596db351cbcd096e",
    created_at: "2025-02-13T23:45:31.713Z",
    updated_at: "2025-02-13T23:45:31.713Z",
    index: "BGKGJLyH",
    name: "Hunter Lyric Vega",
    source: "",
    generic_description: {
      de: "Zane Vega Blaze Aspen Orion Zara Indigo Ember Hawk Hawk Vega Blaze Ryder Aria Hawk Echo Rogue Blaze Onyx Sable Shadow Indigo Rogue Xander Dash Axel Onyx Dash Axel Aspen Raven Onyx Onyx Sable Atlas Rogue Kairos Atlas Kairos Lyric Axel Aspen Jett Atlas Axel Kairos Dash Indigo Echo Sable",
      en: "Raven Echo Atlas Lyric Hunter Ember Lyric Aspen Dash Luna Zane Indigo Dash Kai Sable Phoenix Hawk Onyx Ryder Indigo Axel Shadow Ember Ryder Aspen Nova Rogue Nova Onyx Zane Dante Luna Xander Xander Xander Ryder Jett Phoenix Echo Lyric Titan Raven Titan Titan Ace Nyx Kairos Nyx Indigo Indigo",
      fr: "Shadow Aria Shadow Rogue Zephyr Dash Orion Nyx Aspen Aspen Ace Onyx Sable Phoenix Titan Zane Ember Dash Sable Titan Titan Zane Knox Dante Echo Lyric Storm Nyx Orion Vega Dash Ember Juno Rogue Jett Maverick Maverick Aspen Kairos Sage Kairos Ace Luna Blaze Knox Ryder Echo Orion Ember Titan",
    },
    generic_remediation: {
      de: "Vega Vega Rogue Hawk Orion Xander Ace Orion Skye Xander Blaze Nyx Sable Aspen Axel Sable Kai Blaze Ryder Sage Sage Juno Kairos Kairos Kai Dash Onyx Atlas Luna Knox Ryder Ryder Juno Nyx Hawk Dash Xander Storm Hunter Juno Titan Jett Ace Zara Juno Hawk Hunter Blaze Echo Storm",
      en: "Nova Atlas Onyx Sage Ace Hunter Phoenix Lyric Maverick Skye Raven Jett Luna Nova Skye Indigo Sable Hawk Axel Aria Sable Hunter Ember Axel Ryder Xander Sage Kai Lyric Zephyr Dante Maverick Blaze Juno Aria Zane Sable Juno Sable Hunter Zephyr Zane Jett Knox Ember Kairos Zara Ryder Skye Axel",
      fr: "Titan Sable Indigo Xander Vega Phoenix Zephyr Indigo Zane Titan Vega Vega Phoenix Jett Orion Xander Juno Vega Raven Luna Vega Zara Storm Sage Hunter Aria Hawk Knox Lyric Juno Jett Phoenix Jett Raven Hunter Shadow Phoenix Knox Kairos Aspen Atlas Hawk Storm Sage Indigo Ember Raven Nyx Jett Ember",
    },
  },
  {
    id: "67ae841b596db351cbcd096f",
    created_at: "2025-02-13T23:45:31.829Z",
    updated_at: "2025-02-13T23:45:31.829Z",
    index: "harbVqlm",
    name: "Axel Rogue Titan",
    source: "",
    generic_description: {
      es: "Raven Blaze Vega Xander Dante Hunter Sable Aspen Raven Aspen Nyx Ryder Zara Ryder Echo Onyx Rogue Ryder Hawk Dash Raven Aria Ryder Hunter Maverick Kairos Titan Shadow Nova Storm Titan Rogue Juno Indigo Dash Luna Ace Indigo Lyric Dante Lyric Hawk Echo Phoenix Ace Echo Sable Zara Zephyr Kai",
      fr: "Luna Aria Indigo Orion Phoenix Aspen Kai Shadow Rogue Aspen Onyx Zara Sable Luna Maverick Aspen Hawk Orion Onyx Kai Juno Vega Kai Sable Lyric Kai Shadow Dash Hawk Kai Titan Raven Shadow Juno Aria Maverick Aria Echo Vega Echo Nova Raven Aspen Hawk Ace Dante Hawk Rogue Storm Sage",
      it: "Sable Sable Aria Zara Luna Aspen Titan Nova Echo Hunter Sage Maverick Nova Knox Zephyr Aspen Hunter Phoenix Lyric Hawk Atlas Dash Storm Ryder Nyx Jett Skye Indigo Atlas Nyx Zane Raven Kai Echo Nova Raven Jett Nyx Blaze Vega Aspen Orion Dash Sable Phoenix Blaze Titan Zephyr Lyric Skye",
    },
    generic_remediation: {
      es: "Xander Zane Nyx Blaze Lyric Nyx Xander Aspen Vega Phoenix Aspen Aspen Axel Ember Vega Zane Zephyr Skye Ace Skye Skye Jett Skye Rogue Nova Dash Ryder Nyx Zara Juno Zane Echo Zane Sable Orion Blaze Xander Ace Raven Lyric Hawk Rogue Dash Zephyr Onyx Kai Luna Dante Juno Aria",
      fr: "Storm Shadow Nova Axel Aria Sage Kairos Sage Dante Hawk Zane Vega Dash Atlas Kairos Orion Orion Nova Zara Phoenix Nyx Raven Orion Skye Titan Onyx Ember Raven Nyx Zane Knox Atlas Zane Dante Orion Xander Indigo Knox Axel Atlas Axel Aria Jett Jett Nyx Maverick Raven Raven Rogue Dash",
      it: "Zane Jett Xander Zephyr Kairos Juno Knox Dash Kairos Zane Axel Raven Atlas Aspen Kairos Nova Orion Indigo Indigo Aria Xander Zephyr Lyric Juno Zane Onyx Vega Sage Echo Hunter Kai Skye Aria Kairos Nyx Jett Luna Dash Phoenix Ember Storm Dante Sable Skye Storm Atlas Indigo Dante Storm Ace",
    },
  },
  {
    id: "67ae8421596db351cbcd098b",
    created_at: "2025-02-13T23:45:37.309Z",
    updated_at: "2025-02-13T23:45:37.309Z",
    index: "xSKOMgUW",
    name: "Sable Dash Dante",
    source: "",
    generic_description: {
      en: "Nova Sage Sable Kairos Sable Maverick Nyx Titan Ace Luna Ember Raven Onyx Zara Ace Blaze Storm Ember Titan Zane Lyric Echo Kairos Dash Sable Maverick Shadow Nova Kairos Xander Sable Jett Sable Kai Onyx Aspen Shadow Storm Indigo Ace Storm Aspen Sage Titan Sage Vega Echo Juno Echo Zephyr",
      fr: "Hawk Dante Nova Knox Indigo Storm Blaze Axel Titan Dante Kai Kai Nova Zephyr Sable Skye Sage Xander Phoenix Echo Ryder Vega Zephyr Juno Dante Juno Hawk Aspen Nyx Knox Hunter Lyric Phoenix Axel Axel Jett Nyx Xander Kai Hunter Indigo Echo Orion Shadow Nova Luna Ryder Indigo Lyric Ryder",
      it: "Atlas Skye Storm Kairos Lyric Onyx Aspen Zara Shadow Vega Shadow Lyric Axel Hawk Axel Hawk Orion Blaze Sable Skye Sage Indigo Blaze Ember Xander Dante Zephyr Onyx Knox Hawk Luna Ace Luna Skye Jett Jett Rogue Sable Axel Blaze Luna Indigo Hawk Kai Zara Zane Skye Zane Knox Atlas",
    },
    generic_remediation: {
      en: "Nyx Storm Sage Kairos Hunter Sable Echo Juno Phoenix Jett Echo Jett Jett Zane Rogue Sage Lyric Blaze Indigo Indigo Skye Storm Sage Skye Phoenix Atlas Raven Zane Maverick Dante Storm Nyx Zephyr Zane Indigo Zara Zane Indigo Kairos Aspen Zane Knox Nova Aria Jett Phoenix Shadow Jett Juno Titan",
      fr: "Shadow Echo Aspen Ember Nova Kairos Luna Shadow Knox Vega Dash Titan Jett Zane Titan Zane Skye Vega Vega Ace Storm Jett Hawk Skye Rogue Ryder Ember Shadow Knox Zane Vega Zara Nova Kai Kai Onyx Aria Shadow Indigo Knox Aspen Kairos Titan Luna Shadow Zane Knox Zephyr Xander Rogue",
      it: "Skye Luna Dante Orion Phoenix Nyx Titan Hunter Skye Skye Ryder Vega Luna Onyx Lyric Skye Jett Titan Skye Nyx Storm Juno Aria Titan Indigo Luna Ace Lyric Titan Raven Nova Indigo Sable Zephyr Hawk Maverick Ember Onyx Vega Zephyr Ryder Ember Knox Hunter Sable Zane Phoenix Titan Knox Ryder",
    },
  },
  {
    id: "67ae8421596db351cbcd098c",
    created_at: "2025-02-13T23:45:37.42Z",
    updated_at: "2025-02-13T23:45:37.42Z",
    index: "ObQGtIsM",
    name: "Titan Jett Skye",
    source: "",
    generic_description: {
      de: "Hawk Ace Orion Onyx Indigo Dante Knox Phoenix Atlas Indigo Dante Ryder Juno Phoenix Aria Dante Maverick Titan Storm Orion Phoenix Vega Raven Orion Raven Echo Luna Onyx Echo Ryder Sable Echo Dante Rogue Luna Kairos Shadow Titan Onyx Rogue Zane Luna Blaze Aspen Jett Zephyr Indigo Phoenix Maverick Blaze",
      en: "Echo Knox Knox Hawk Maverick Kai Hawk Kairos Skye Dante Jett Xander Dante Nova Axel Zephyr Onyx Dante Lyric Orion Aria Rogue Kai Onyx Aspen Titan Nyx Hawk Onyx Luna Axel Skye Dante Kairos Vega Rogue Kai Luna Raven Sable Knox Orion Hawk Maverick Rogue Luna Kai Phoenix Lyric Shadow",
      fr: "Nova Lyric Xander Indigo Indigo Sable Dante Aspen Dash Raven Nyx Nova Phoenix Dante Blaze Nova Sage Shadow Ryder Nova Orion Lyric Ryder Kai Knox Luna Zane Lyric Shadow Zephyr Nyx Maverick Shadow Aspen Axel Titan Knox Titan Vega Lyric Phoenix Titan Echo Juno Shadow Atlas Blaze Orion Axel Orion",
    },
    generic_remediation: {
      de: "Juno Atlas Nova Zephyr Zane Kairos Rogue Nova Lyric Shadow Knox Lyric Dash Zephyr Nyx Orion Lyric Echo Orion Ace Onyx Skye Knox Titan Dante Axel Hawk Orion Zane Atlas Blaze Jett Zane Shadow Aria Zane Maverick Vega Nyx Nova Ember Juno Indigo Nyx Axel Raven Nova Titan Xander Zane",
      en: "Kai Zane Blaze Aria Sage Echo Axel Rogue Onyx Phoenix Kai Blaze Onyx Shadow Aria Hawk Kairos Raven Storm Ember Hawk Maverick Zane Kairos Dash Xander Orion Atlas Maverick Hunter Dash Skye Atlas Raven Luna Aspen Aria Knox Nova Sable Titan Orion Atlas Hunter Zephyr Kai Phoenix Skye Zephyr Kai",
      fr: "Jett Blaze Nova Rogue Lyric Phoenix Axel Hunter Juno Dash Ryder Sage Luna Nyx Jett Aspen Jett Kairos Kairos Rogue Sable Nova Hunter Nyx Echo Zane Aria Zane Hunter Orion Hunter Raven Echo Atlas Sable Phoenix Jett Juno Titan Vega Axel Ryder Zane Axel Sage Nyx Zara Indigo Aspen Maverick",
    },
  },
  {
    id: "67ae8421596db351cbcd098d",
    created_at: "2025-02-13T23:45:37.485Z",
    updated_at: "2025-02-13T23:45:37.485Z",
    index: "JePezfCg",
    name: "Phoenix Nova Dante",
    source: "",
    generic_description: {
      de: "Skye Phoenix Dante Phoenix Knox Zephyr Skye Aria Xander Knox Axel Xander Titan Zara Axel Zara Lyric Onyx Aspen Hawk Axel Hunter Luna Skye Kai Orion Raven Ace Zara Xander Luna Kai Sable Nova Sage Phoenix Juno Ryder Nyx Juno Skye Jett Ember Sable Onyx Juno Dash Ember Zara Rogue",
      en: "Rogue Skye Hawk Shadow Orion Storm Zephyr Ace Nova Raven Vega Shadow Orion Sable Ace Dash Hawk Lyric Blaze Onyx Zara Knox Aspen Ryder Ember Blaze Nyx Vega Zane Atlas Maverick Sage Juno Skye Zara Shadow Indigo Zephyr Kairos Xander Rogue Skye Hunter Jett Raven Lyric Knox Axel Luna Vega",
      es: "Juno Hawk Vega Onyx Storm Ember Aspen Dante Storm Hawk Vega Axel Shadow Xander Dash Aspen Nyx Maverick Hawk Ember Aspen Xander Knox Phoenix Luna Ace Ace Xander Maverick Ace Lyric Kai Nova Nova Raven Dash Dante Zane Storm Rogue Titan Raven Nyx Knox Phoenix Axel Shadow Kai Sable Skye",
      fr: "Phoenix Hawk Indigo Jett Ace Sage Lyric Titan Xander Onyx Vega Zara Atlas Raven Onyx Ace Hunter Rogue Maverick Onyx Phoenix Echo Knox Lyric Hunter Sage Orion Hunter Sable Sable Sable Luna Nyx Aspen Skye Ryder Ryder Atlas Dash Rogue Phoenix Hunter Luna Hunter Orion Maverick Xander Dash Raven Xander",
    },
    generic_remediation: {
      de: "Ember Zara Dash Nyx Ryder Storm Ryder Orion Shadow Phoenix Maverick Echo Juno Juno Maverick Orion Aspen Blaze Indigo Ace Aspen Maverick Luna Kai Aspen Aria Orion Vega Raven Ryder Dash Storm Nyx Zane Ember Sable Dante Ember Nova Phoenix Atlas Luna Titan Xander Sage Vega Xander Luna Aria Maverick",
      en: "Dash Storm Nova Dante Hawk Skye Aria Knox Kairos Jett Rogue Storm Maverick Blaze Kai Shadow Zara Aria Skye Storm Nyx Storm Knox Knox Ryder Kairos Zara Shadow Luna Ember Lyric Storm Skye Nyx Ember Kairos Sage Raven Nyx Onyx Sable Nyx Zephyr Dash Dash Phoenix Zara Dante Hawk Aspen",
      es: "Aspen Maverick Jett Kai Kai Ryder Lyric Knox Atlas Raven Sable Orion Zane Hunter Zara Raven Zephyr Maverick Juno Luna Titan Hawk Blaze Zephyr Storm Zane Phoenix Phoenix Luna Luna Jett Dante Sable Luna Atlas Orion Dash Hunter Sage Nyx Kai Aria Zephyr Blaze Zane Kai Rogue Aria Zane Jett",
      fr: "Zara Sable Jett Orion Ace Raven Shadow Blaze Sable Vega Vega Dante Jett Phoenix Lyric Skye Sage Dash Indigo Blaze Kai Blaze Phoenix Shadow Maverick Titan Knox Orion Juno Storm Zephyr Nyx Knox Maverick Storm Shadow Shadow Zephyr Ryder Blaze Hawk Axel Aspen Zara Onyx Maverick Vega Dante Zephyr Nyx",
    },
  },
  {
    id: "67ae8421596db351cbcd098e",
    created_at: "2025-02-13T23:45:37.593Z",
    updated_at: "2025-02-13T23:45:37.593Z",
    index: "BJTfTMxc",
    name: "Ace Luna Sage",
    source: "",
    generic_description: {
      de: "Echo Dash Blaze Zephyr Juno Lyric Knox Raven Juno Titan Ryder Onyx Sage Sage Echo Vega Rogue Skye Zara Aspen Orion Kairos Luna Dash Ace Aspen Blaze Juno Ryder Vega Echo Lyric Echo Dante Zara Echo Jett Raven Echo Hawk Dash Vega Storm Ace Axel Dante Atlas Aria Dante Shadow",
      en: "Nyx Knox Storm Dash Echo Jett Nova Knox Rogue Sage Phoenix Orion Xander Zephyr Xander Orion Phoenix Storm Aspen Hunter Juno Echo Echo Aria Knox Shadow Kai Zephyr Ryder Luna Titan Aria Hunter Zephyr Kai Rogue Ember Dash Hawk Zephyr Sable Indigo Maverick Hunter Zara Ryder Dash Luna Rogue Atlas",
      es: "Sage Knox Indigo Sable Axel Ryder Raven Luna Ember Hawk Orion Hawk Storm Juno Axel Onyx Zara Ember Luna Aspen Phoenix Axel Raven Atlas Kairos Kai Shadow Jett Dash Hawk Zephyr Shadow Dante Luna Skye Dash Hawk Zephyr Blaze Raven Echo Ace Sable Echo Storm Storm Skye Dante Echo Luna",
    },
    generic_remediation: {
      de: "Axel Xander Maverick Maverick Raven Maverick Orion Atlas Zara Zara Xander Zara Kai Aria Dash Ace Ryder Titan Storm Nova Ember Orion Ace Maverick Nyx Raven Orion Blaze Dash Zara Zephyr Phoenix Aspen Aria Jett Hawk Titan Ember Aspen Ace Zane Shadow Dash Xander Luna Sable Jett Vega Zara Zephyr",
      en: "Ember Zephyr Onyx Zephyr Onyx Echo Titan Zara Raven Dash Aspen Axel Nyx Rogue Kairos Juno Maverick Juno Phoenix Nyx Ryder Jett Raven Zephyr Jett Xander Nova Dante Juno Raven Xander Titan Zara Kai Rogue Skye Zara Orion Dash Luna Juno Ember Atlas Lyric Knox Skye Nyx Onyx Luna Xander",
      es: "Orion Zane Rogue Blaze Raven Knox Zara Skye Shadow Luna Juno Orion Titan Ember Maverick Hunter Xander Knox Dante Ace Luna Shadow Kai Jett Axel Zara Titan Ryder Maverick Storm Raven Atlas Titan Ember Dash Jett Blaze Jett Raven Dash Zane Titan Maverick Sage Sable Ace Juno Lyric Phoenix Shadow",
    },
  },
  {
    id: "67ae8421596db351cbcd098f",
    created_at: "2025-02-13T23:45:37.7Z",
    updated_at: "2025-02-13T23:45:37.7Z",
    index: "JFxhLaEy",
    name: "Ryder Indigo Zara",
    source: "",
    generic_description: {
      de: "Shadow Aspen Juno Indigo Aria Vega Phoenix Rogue Hunter Indigo Echo Zephyr Storm Ryder Storm Onyx Sable Skye Ryder Sable Onyx Orion Kairos Ember Echo Rogue Zara Vega Juno Ember Ryder Dante Zane Sable Dante Sage Aria Rogue Zephyr Phoenix Luna Zara Dash Storm Storm Lyric Zara Ace Lyric Shadow",
      en: "Nyx Hawk Phoenix Vega Nyx Sable Raven Sable Orion Juno Hawk Knox Hawk Sable Dash Knox Sable Rogue Ryder Jett Ace Maverick Zane Aspen Luna Kairos Aria Aria Blaze Ace Storm Titan Kai Dash Aspen Orion Ace Axel Sable Raven Storm Luna Blaze Vega Jett Vega Storm Sage Nyx Zephyr",
      es: "Ryder Xander Kai Phoenix Atlas Titan Jett Storm Axel Sage Aria Zephyr Sage Ember Maverick Hunter Kai Dante Indigo Aria Juno Kairos Sable Knox Juno Ryder Zephyr Kairos Ryder Atlas Vega Dante Luna Hawk Maverick Ace Dante Knox Indigo Zara Indigo Hunter Zane Zane Dash Orion Raven Nyx Xander Raven",
    },
    generic_remediation: {
      de: "Kai Jett Zane Hunter Xander Sage Vega Zane Nova Nova Rogue Rogue Sable Titan Dante Axel Kairos Rogue Dash Ryder Axel Knox Onyx Raven Titan Orion Xander Ryder Echo Orion Sage Aspen Raven Onyx Zane Nova Titan Lyric Storm Jett Kai Raven Dante Rogue Rogue Raven Dash Sage Rogue Dash",
      en: "Titan Hawk Dash Nova Xander Storm Echo Lyric Sage Aria Aria Zara Shadow Ember Kai Dante Blaze Dante Juno Shadow Nova Axel Skye Shadow Sage Ryder Onyx Nyx Skye Skye Lyric Kairos Nova Jett Skye Zara Zephyr Indigo Raven Nova Nyx Hunter Hawk Dante Raven Lyric Lyric Juno Indigo Dante",
      es: "Sable Orion Skye Lyric Indigo Ryder Axel Juno Zephyr Orion Maverick Kairos Raven Axel Zara Dante Onyx Aspen Zane Blaze Raven Aspen Xander Vega Xander Aria Dash Zephyr Kairos Knox Maverick Jett Orion Skye Titan Shadow Lyric Kairos Ember Luna Jett Zephyr Luna Skye Juno Echo Juno Skye Hunter Axel",
    },
  },
  {
    id: "67ae8430596db351cbcd09ab",
    created_at: "2025-02-13T23:45:52.544Z",
    updated_at: "2025-02-13T23:45:52.544Z",
    index: "xuuYqGfe",
    name: "Shadow Storm Sable",
    source: "",
    generic_description: {
      en: "Sage Nova Sage Ember Zephyr Hawk Skye Axel Indigo Zara Indigo Orion Sage Jett Aspen Echo Vega Maverick Vega Hawk Dante Onyx Maverick Shadow Onyx Luna Kai Nova Raven Skye Axel Dash Hawk Knox Storm Xander Maverick Sable Titan Orion Ember Vega Sage Aspen Orion Indigo Blaze Raven Axel Hunter",
      fr: "Hawk Nova Ember Nyx Dante Onyx Aspen Nova Jett Storm Orion Vega Rogue Juno Zephyr Maverick Hawk Lyric Nova Zane Hawk Ace Zephyr Maverick Hawk Zephyr Skye Jett Storm Xander Dash Titan Vega Blaze Nyx Echo Aspen Zara Ember Aspen Atlas Hunter Zara Lyric Lyric Axel Sage Ryder Atlas Onyx",
      it: "Luna Phoenix Aspen Juno Knox Indigo Aspen Hunter Ace Blaze Zane Rogue Blaze Indigo Knox Phoenix Hawk Maverick Shadow Onyx Onyx Hawk Skye Onyx Ember Phoenix Zephyr Nova Rogue Echo Zane Skye Skye Kai Aria Dash Ember Kai Skye Vega Storm Ryder Dash Vega Orion Ember Kai Knox Dash Sable",
    },
    generic_remediation: {
      en: "Shadow Lyric Sable Aspen Ace Kairos Ember Nova Nova Shadow Indigo Sable Lyric Aria Aspen Kai Aria Juno Ryder Dante Hawk Nova Kai Skye Dante Indigo Onyx Lyric Onyx Hunter Ace Kairos Raven Knox Ember Aria Juno Sage Dash Orion Ace Orion Sable Kairos Aria Phoenix Ace Xander Hawk Orion",
      fr: "Axel Knox Maverick Kai Sage Phoenix Vega Hawk Aria Zephyr Atlas Indigo Lyric Luna Orion Dante Kai Knox Juno Jett Lyric Kairos Storm Kai Rogue Orion Ace Onyx Dash Aria Titan Dash Dash Sage Knox Phoenix Shadow Nyx Storm Ember Orion Storm Onyx Knox Dash Kairos Aspen Storm Kai Shadow",
      it: "Titan Jett Ace Lyric Ryder Hunter Shadow Zane Maverick Luna Zane Ryder Aria Phoenix Dante Lyric Zane Storm Jett Luna Phoenix Zephyr Luna Ryder Hawk Titan Xander Lyric Nova Sage Kairos Vega Onyx Nyx Orion Zane Zephyr Sage Zane Sage Dash Hawk Kai Sable Sable Titan Kairos Blaze Nyx Jett",
    },
  },
  {
    id: "67ae8430596db351cbcd09ac",
    created_at: "2025-02-13T23:45:52.657Z",
    updated_at: "2025-02-13T23:45:52.657Z",
    index: "uyuVUawI",
    name: "Aspen Zara Zara",
    source: "",
    generic_description: {
      en: "Echo Sable Blaze Ace Jett Echo Phoenix Aspen Aria Aspen Phoenix Aspen Jett Skye Echo Aspen Juno Zephyr Phoenix Skye Echo Knox Sable Echo Ace Jett Maverick Dante Phoenix Atlas Aria Echo Dante Dante Zara Sable Hunter Blaze Ace Kai Zephyr Sage Vega Onyx Atlas Phoenix Skye Jett Zane Echo",
      fr: "Juno Nova Knox Zara Atlas Kairos Ember Zara Sage Kai Zephyr Kai Skye Zephyr Raven Zane Zane Zephyr Blaze Sage Aspen Knox Sable Orion Ember Hunter Lyric Storm Sage Phoenix Maverick Orion Ember Nova Rogue Juno Lyric Kai Sable Dash Skye Axel Rogue Lyric Dante Ryder Lyric Orion Ace Sable",
      it: "Aria Phoenix Ember Onyx Phoenix Jett Rogue Xander Vega Knox Dante Jett Phoenix Indigo Orion Kai Hunter Dante Ember Dash Skye Sable Rogue Dash Titan Knox Luna Sable Orion Echo Kai Atlas Rogue Raven Juno Onyx Jett Luna Nyx Dante Nyx Jett Xander Zephyr Zara Maverick Echo Orion Orion Vega",
    },
    generic_remediation: {
      en: "Jett Nyx Ryder Nova Atlas Blaze Shadow Zephyr Aria Titan Knox Maverick Luna Rogue Shadow Hunter Rogue Maverick Orion Blaze Dash Zephyr Ember Skye Sage Storm Zane Maverick Lyric Skye Lyric Kai Xander Onyx Storm Ace Sable Atlas Zane Sage Ace Titan Xander Axel Luna Sage Jett Nyx Nyx Hunter",
      fr: "Indigo Dash Dante Hunter Atlas Hunter Maverick Knox Phoenix Ryder Aria Aspen Aria Sage Rogue Kai Juno Shadow Skye Nova Nova Ember Maverick Jett Storm Dante Raven Dash Aspen Skye Xander Axel Atlas Titan Ryder Zara Maverick Ryder Blaze Nova Orion Juno Ryder Xander Aspen Ryder Phoenix Juno Xander Ryder",
      it: "Nyx Aspen Storm Jett Hawk Luna Zephyr Xander Jett Sable Atlas Indigo Onyx Axel Lyric Atlas Hawk Luna Sage Juno Zephyr Zane Maverick Kairos Raven Nova Echo Shadow Kai Ace Nyx Nyx Zara Atlas Dash Zane Hunter Lyric Echo Dante Lyric Zara Jett Zara Nyx Maverick Maverick Hawk Blaze Raven",
    },
  },
  {
    id: "67ae8430596db351cbcd09ad",
    created_at: "2025-02-13T23:45:52.773Z",
    updated_at: "2025-02-13T23:45:52.773Z",
    index: "QGQXEmJW",
    name: "Zara Maverick Sable",
    source: "",
    generic_description: {
      de: "Aria Maverick Shadow Dante Aria Jett Jett Nyx Kai Ryder Onyx Maverick Skye Kai Zara Onyx Nova Raven Ryder Echo Luna Sable Nova Rogue Hunter Aspen Sable Aspen Lyric Aria Dante Sage Aspen Storm Echo Luna Dante Maverick Skye Aspen Raven Sage Storm Zara Rogue Sable Zephyr Lyric Kairos Orion",
      en: "Atlas Hawk Skye Titan Echo Lyric Axel Shadow Ace Ryder Raven Maverick Blaze Nyx Ace Aspen Luna Xander Maverick Onyx Zane Axel Onyx Onyx Titan Sage Dash Zara Lyric Nyx Kai Luna Atlas Sable Titan Indigo Sage Dante Aria Indigo Atlas Aria Storm Atlas Shadow Juno Atlas Xander Shadow Aria",
      it: "Hunter Storm Sage Vega Lyric Phoenix Kairos Rogue Juno Raven Axel Storm Zara Indigo Rogue Sage Kai Onyx Zephyr Blaze Ember Luna Dash Xander Kairos Aria Juno Ryder Phoenix Raven Sable Kairos Lyric Echo Echo Axel Luna Shadow Storm Kai Dash Vega Echo Ember Shadow Dante Hawk Hunter Zephyr Juno",
    },
    generic_remediation: {
      de: "Hunter Lyric Rogue Aria Dash Vega Hunter Ember Dante Nova Jett Zephyr Dash Rogue Indigo Sable Kai Jett Raven Storm Aspen Aspen Raven Dante Blaze Shadow Dash Atlas Atlas Xander Zane Luna Vega Kairos Sage Hunter Jett Juno Raven Aspen Echo Dash Dante Vega Titan Maverick Rogue Ember Sable Atlas",
      en: "Vega Sable Zara Axel Vega Kairos Indigo Shadow Ember Indigo Blaze Zara Luna Nyx Kai Juno Luna Indigo Zane Phoenix Ace Knox Axel Luna Hawk Hawk Zane Ember Ryder Nova Kairos Juno Nova Echo Hunter Ace Shadow Ace Kai Indigo Shadow Aria Ryder Ryder Kai Kairos Sage Storm Shadow Ryder",
      it: "Ace Blaze Lyric Nova Raven Jett Hawk Rogue Ember Jett Shadow Kai Zane Echo Zane Sable Axel Ace Juno Ryder Zephyr Axel Raven Axel Sable Titan Atlas Titan Shadow Zane Shadow Ember Ace Sable Ace Juno Rogue Sage Dante Vega Onyx Dash Orion Kairos Knox Orion Aspen Nova Zephyr Maverick",
    },
  },
  {
    id: "67ae8430596db351cbcd09ae",
    created_at: "2025-02-13T23:45:52.889Z",
    updated_at: "2025-02-13T23:45:52.889Z",
    index: "UfxCrZZt",
    name: "Titan Kairos Raven",
    source: "",
    generic_description: {
      de: "Maverick Aspen Zephyr Maverick Sable Blaze Blaze Zane Sage Kai Skye Maverick Raven Skye Echo Knox Rogue Nova Sage Juno Dante Skye Nyx Zara Zane Storm Axel Xander Onyx Rogue Kai Dash Luna Skye Orion Skye Nova Kai Zane Atlas Zara Vega Ryder Lyric Xander Vega Skye Jett Knox Zara",
      en: "Onyx Dante Raven Raven Raven Kairos Aria Rogue Rogue Sage Knox Kai Ace Ace Aria Dante Titan Dante Nyx Zane Blaze Orion Atlas Axel Raven Echo Orion Zara Nyx Storm Kai Aria Vega Maverick Axel Zara Aspen Raven Ace Maverick Shadow Vega Storm Xander Aria Echo Maverick Zane Juno Kairos",
      es: "Titan Kai Zephyr Phoenix Rogue Zane Kairos Atlas Luna Blaze Ember Knox Raven Ryder Shadow Zephyr Zane Dash Indigo Dante Aria Blaze Indigo Nova Axel Zephyr Vega Axel Dash Onyx Rogue Axel Xander Dash Jett Nyx Atlas Vega Aspen Atlas Luna Dash Zane Raven Juno Indigo Atlas Hawk Knox Knox",
      fr: "Dante Raven Orion Aspen Echo Sable Axel Ember Dash Phoenix Ace Kairos Hawk Zephyr Luna Phoenix Lyric Ace Lyric Blaze Aria Echo Dash Maverick Jett Titan Juno Vega Vega Phoenix Knox Axel Rogue Sable Blaze Nova Ryder Axel Titan Xander Titan Ace Aspen Ace Sage Dante Blaze Atlas Indigo Sable",
    },
    generic_remediation: {
      de: "Aspen Skye Lyric Aspen Hawk Xander Indigo Sage Zane Blaze Skye Lyric Echo Dante Hawk Blaze Kai Dante Kairos Sage Atlas Maverick Dash Echo Ace Lyric Skye Nova Onyx Aria Aspen Rogue Axel Rogue Ryder Rogue Kairos Titan Lyric Sage Axel Skye Zane Aspen Dash Indigo Axel Dante Maverick Ace",
      en: "Raven Jett Kairos Dante Blaze Onyx Ryder Luna Maverick Titan Aspen Aria Ember Luna Nyx Xander Nova Skye Blaze Sage Ryder Rogue Zara Hawk Kairos Jett Luna Zane Aria Axel Kairos Nova Knox Zephyr Nyx Jett Raven Onyx Indigo Xander Xander Aspen Phoenix Axel Hunter Titan Sage Maverick Vega Sable",
      es: "Luna Sage Dash Axel Echo Ryder Axel Dash Maverick Xander Echo Skye Ember Shadow Atlas Knox Rogue Knox Vega Ryder Titan Storm Juno Phoenix Ace Sable Vega Aspen Nova Maverick Phoenix Ryder Ryder Dash Luna Skye Skye Knox Orion Indigo Axel Hunter Zephyr Ryder Hunter Orion Juno Rogue Storm Ember",
      fr: "Atlas Shadow Echo Orion Onyx Juno Titan Shadow Shadow Aria Ember Axel Zara Sable Phoenix Aria Aria Aspen Raven Juno Sable Phoenix Kai Titan Xander Juno Hawk Vega Dash Aria Zane Hawk Zane Sage Zane Aspen Dash Zara Titan Ryder Kai Blaze Zane Shadow Luna Titan Zara Xander Atlas Orion",
    },
  },
  {
    id: "67ae8431596db351cbcd09af",
    created_at: "2025-02-13T23:45:53.005Z",
    updated_at: "2025-02-13T23:45:53.005Z",
    index: "dMJCagnJ",
    name: "Titan Nyx Luna",
    source: "",
    generic_description: {
      de: "Phoenix Raven Sage Sage Ryder Luna Onyx Ryder Nyx Juno Raven Echo Zara Xander Axel Aspen Luna Echo Dash Ryder Aspen Zane Sable Echo Axel Ryder Storm Dash Nova Shadow Luna Ryder Sable Aria Nyx Phoenix Nova Vega Juno Dante Hunter Skye Blaze Storm Raven Atlas Echo Zane Lyric Nyx",
      es: "Ace Sage Maverick Luna Raven Luna Aria Zephyr Titan Indigo Aspen Vega Luna Onyx Sable Ryder Storm Xander Luna Dante Knox Nova Orion Axel Echo Juno Sage Aria Phoenix Orion Vega Lyric Shadow Aria Nova Dash Raven Luna Hunter Onyx Echo Hawk Zephyr Sage Dante Dante Ember Storm Maverick Xander",
      it: "Shadow Hunter Jett Ryder Ace Storm Atlas Ember Vega Titan Hawk Orion Storm Ryder Xander Xander Nyx Storm Zephyr Sable Indigo Ember Axel Blaze Echo Ember Dante Shadow Kairos Sable Zara Zara Zephyr Indigo Onyx Maverick Zane Shadow Maverick Sage Axel Echo Sage Axel Echo Orion Ember Titan Echo Luna",
    },
    generic_remediation: {
      de: "Hawk Orion Onyx Zara Nova Nyx Aria Aspen Dash Jett Xander Rogue Ace Aria Phoenix Zephyr Kai Knox Sable Zephyr Sable Ace Sable Knox Kai Luna Indigo Atlas Aspen Blaze Indigo Orion Rogue Sable Phoenix Aria Axel Juno Lyric Axel Sage Maverick Juno Dante Aspen Atlas Echo Phoenix Nova Nyx",
      es: "Aria Lyric Dante Axel Indigo Knox Dante Rogue Shadow Titan Ryder Ember Hunter Onyx Zane Titan Zane Nyx Titan Blaze Ace Hunter Zephyr Sable Sage Shadow Dash Aspen Juno Orion Ryder Orion Aspen Indigo Dash Xander Vega Luna Axel Ryder Sable Juno Atlas Titan Maverick Jett Kairos Sage Zephyr Xander",
      it: "Zephyr Storm Jett Titan Juno Zane Kairos Atlas Zane Nova Zephyr Titan Hawk Kairos Ember Shadow Axel Xander Dash Sage Sable Blaze Sable Nova Indigo Sable Ace Lyric Shadow Nyx Indigo Zane Zephyr Onyx Ember Ace Atlas Kai Titan Juno Rogue Orion Aspen Sage Vega Orion Kai Sage Skye Skye",
    },
  },
];
