export const vulnerabilities = [
  {
    id: "67ae841c596db351cbcd0971",
    created_at: "2025-02-13T23:45:32.011Z",
    updated_at: "2025-02-13T23:45:32.011Z",
    category: { id: "67ae841b596db351cbcd096e", index: "BGKGJLyH", name: "Hunter Lyric Vega" },
    detailed_title: "AoOLABtk",
    cvss_vector: "CVSS:3.1/AV:N/AC:H/PR:L/UI:R/S:C/C:L/I:L/A:H",
    cvss_score: 7.1,
    cvss_severity: "High",
    cvss_description:
      "An attacker with limited privileges, using a Network vector, can potentially carry out high complexity attacks resulting in low on confidentiality, low on integrity, and high on availability. The attacks require user interaction, and a successful attack may lead to a scope change.",
    references: ["https://example.fr", "https://example.gov"],
    generic_description: {
      enabled: true,
      text: "Raven Echo Atlas Lyric Hunter Ember Lyric Aspen Dash Luna Zane Indigo Dash Kai Sable Phoenix Hawk Onyx Ryder Indigo Axel Shadow Ember Ryder Aspen Nova Rogue Nova Onyx Zane Dante Luna Xander Xander Xander Ryder Jett Phoenix Echo Lyric Titan Raven Titan Titan Ace Nyx Kairos Nyx Indigo Indigo",
    },
    generic_remediation: {
      enabled: true,
      text: "Nova Atlas Onyx Sage Ace Hunter Phoenix Lyric Maverick Skye Raven Jett Luna Nova Skye Indigo Sable Hawk Axel Aria Sable Hunter Ember Axel Ryder Xander Sage Kai Lyric Zephyr Dante Maverick Blaze Juno Aria Zane Sable Juno Sable Hunter Zephyr Zane Jett Knox Ember Kairos Zara Ryder Skye Axel",
    },
    description: "OEkfwyka",
    remediation: "TbAfHdIg",
    target: { id: "67ae841a596db351cbcd0961", ip: "48.46.250.52", hostname: "TOZTlSTW.gov" },
    assessment: { id: "67ae841b596db351cbcd0969", name: "Lyric Blaze Juno" },
    user: { id: "67ae8408596db351cbcd094f", username: "kryvea" },
  },
  {
    id: "67ae841c596db351cbcd0973",
    created_at: "2025-02-13T23:45:32.198Z",
    updated_at: "2025-02-13T23:45:32.198Z",
    category: { id: "67ae841b596db351cbcd096d", index: "DDXcRBAC", name: "Onyx Zane Zephyr" },
    detailed_title: "dGmtUtGN",
    cvss_vector: "CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:N/I:H/A:N",
    cvss_score: 4.2,
    cvss_severity: "Medium",
    cvss_description:
      "An attacker with high privileges, using a Adjacent Network vector, can potentially carry out high complexity attacks resulting in no impact on confidentiality, high on integrity, and no impact on availability. The attacks do not require user interaction, and a successful attack may remain confined within the same component.",
    references: ["https://example.uk", "https://example.uk", "https://example.it"],
    generic_description: {
      enabled: true,
      text: "Hunter Sage Zane Lyric Xander Ryder Hawk Axel Phoenix Xander Zara Shadow Indigo Knox Ryder Xander Dante Skye Lyric Vega Knox Sage Phoenix Lyric Knox Ryder Indigo Nova Jett Luna Onyx Ryder Dash Zane Raven Nyx Lyric Hunter Onyx Raven Nova Zara Ace Aria Lyric Hawk Vega Skye Maverick Ace",
    },
    generic_remediation: {
      enabled: true,
      text: "Aspen Phoenix Atlas Jett Hawk Jett Luna Sage Skye Atlas Zephyr Zara Xander Luna Sable Kai Aspen Kai Ryder Luna Maverick Ember Echo Lyric Echo Aria Juno Sable Hawk Dante Echo Sable Jett Sable Blaze Jett Dante Aria Axel Lyric Shadow Maverick Blaze Indigo Luna Kai Nova Ember Aria Nyx",
    },
    description: "eTuaynDv",
    remediation: "RHMQZfXs",
    target: { id: "67ae841a596db351cbcd0960", ip: "223.129.31.203", hostname: "jzUUeYWY.es" },
    assessment: { id: "67ae841b596db351cbcd0969", name: "Lyric Blaze Juno" },
    user: { id: "67ae8408596db351cbcd094f", username: "kryvea" },
  },
  {
    id: "67ae841c596db351cbcd0974",
    created_at: "2025-02-13T23:45:32.31Z",
    updated_at: "2025-02-13T23:45:32.31Z",
    category: { id: "67ae841b596db351cbcd096f", index: "harbVqlm", name: "Axel Rogue Titan" },
    detailed_title: "YphjJMQJ",
    cvss_vector: "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:N/I:L/A:N",
    cvss_score: 2.5,
    cvss_severity: "Low",
    cvss_description:
      "An attacker with limited privileges, using a Local vector, can potentially carry out high complexity attacks resulting in no impact on confidentiality, low on integrity, and no impact on availability. The attacks do not require user interaction, and a successful attack may remain confined within the same component.",
    references: ["https://example.com"],
    generic_description: { enabled: true, text: "" },
    generic_remediation: { enabled: true, text: "" },
    description: "geViklum",
    remediation: "pgBAYqlg",
    target: { id: "67ae841a596db351cbcd0965", ip: "24.121.143.99", hostname: "lqodpZpU.net" },
    assessment: { id: "67ae841b596db351cbcd0969", name: "Lyric Blaze Juno" },
    user: { id: "67ae8408596db351cbcd094f", username: "kryvea" },
  },
];
